language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - jruby-head
  - rbx
  - ruby-head

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
script: bundle exec rspec